Use `Vector2.storage` directly instead of `_v2storage`
google/vector_math.dart pull request #283
Opened 2023-02-28 13:01 UTC by spydon

It is currently hard to extend `Vector2` and make use of its full potential due to the private field `_v2storage`, in this PR we use the `storage` field directly instead. This PR also refactors the factory constructors to be redirection constructors instead.

If this is accepted I can do this for the remaining classes too.

Closes #282

2023-03-01 23:58 UTC, johnmccutchan approved these changes

2023-03-02 07:04 UTC, spydon commented
@johnmccutchan thanks for the review! I'll go ahead and do the same for the rest of the classes then?

2023-03-06 20:56 UTC, rakudrama commented
I am against this change on the grounds discussed at https://github.com/google/vector_math.dart/issues/282#issuecomment-1456971563

2023-03-06 20:58 UTC, rakudrama requested changes
https://github.com/google/vector_math.dart/issues/282#issuecomment-1456971563

2023-03-08 21:05 UTC, closed without merging